### PR TITLE
Merge v1.1 from dhawes/v1.1 to Jasig/master

### PR DESCRIPTION
**Pull request by forsetti**
Prepare for v1.1 RC1

- Introduces Apache httpd 2.4 support
- Other bugfixes

Need LGTM from @pames @smaresca 

Addresses #86 #60 #82 #77

### CODE REVIEW

**Comment by serac** [comment]
+1
I guess it's more symbolic than anything, but I trust Dave and all the fixes he's looped in are good ones that would move the project forward.

**Comment by forsetti** [comment]
Updated jasig/mod_auth_cas to v1.1-RC1

**Comment by ikogan** [comment]
I see that there's some preparation work happening for the 1.1 release and that this PR was closed. Is there a plan to integrate the branch where this came from? I have some changes based on that branch I'd like to open a PR for but I'm not sure when/where to direct those.

**Comment by dhawes** [comment]
The changes in this PR have been merged into Jasig:master. There may be a couple of more commits before v1.1 is tagged, but a PR against master is probably the right place for now.

**Comment by ikogan** [comment]
Okay, I noticed some more work went into that conflicts with some of the things I did, so I'll be working to change things a bit. It looks like you're not interested in packaging (Red Hat, Debian) being in this repo, is that correct?

**Comment by forsetti** [comment]
That is correct -- we'd like to leave the distro packaging outside this
repo.  That is generally preferred by the distro packagers too, so they
don't have to remove anything before beginning their local packaging
process.

On Mon, Feb 1, 2016 at 4:19 PM, Ilya Kogan <notifications@github.com> wrote:

> Okay, I noticed some more work went into that conflicts with some of the
> things I did, so I'll be working to change things a bit. It looks like
> you're not interested in packaging (Red Hat, Debian) being in this repo, is
> that correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jasig/mod_auth_cas/pull/87#issuecomment-178198002>.
>



-- 
matt@forsetti.com
PGP: E2144AD8

**Comment by ikogan** [comment]
Thanks, is there a place I can go to for the packaging files? Ideally something I can add to an automated build?

**Comment by forsetti** [comment]
The distro packaging is not done by the core mod_auth_cas team.  The best I
can suggest is to look at the source archives for Debian and Fedora, which
would likely offer some direction on where each maintainer keeps their repo

**Pull request closed without merging**
