### PR TITLE
Bugfix: Repair NULL deref error in SAML 1.1 response parsing

### PR DESCRIPTION
**Pull request by smaresca**
#### Bugfix summary:
Segmentation fault occurred while preparing a cache entry; username from CAS ticket was never properly extracted, leaving the char* as a NULL banana peel. Full fix required improved parsing of the SAML 1.1 response and addition of some sanity checks.

#### Changes:
* Root cause located in isValidCasTicket() - when AuthenticationStatement contains user name, parse properly (even if saml validation response has no attributes)
* when no username parsed during SAML examination of isValidCASTicket, return FALSE so that its caller throws a "Authorization Required"
* hedge bets and check for valid username set in createCASCookie and writeCASCacheEntry
* AuthenticationMethod has no attributes, so prevent misuse of node attributes as identity attributes
*warn if no attributes available for authorization (e.g., attributes not released by CAS server config)

#### Stack trace:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff799496b in apr_xml_quote_string () from /usr/lib/libaprutil-1.so.0
(gdb) bt
0  0x00007ffff799496b in apr_xml_quote_string () from /usr/lib/libaprutil-1.so.0
1  0x00007ffff62e830e in writeCASCacheEntry (r=0x7ffff53c30a0, name=0x7ffff53c2780 "1b3855f0110f1a05d3ca5d2c5667b6e3", cache=0x7fffffffdc60, exists=0 '\000')
   at mod_auth_cas.c:1215
2  0x00007ffff62e9635 in createCASCookie (r=0x7ffff53c30a0, user=0x0, attrs=0x7ffff53ccb50, ticket=0x7ffff53cb277 "ST-701585-TK73aKTv4yzBo1bcY6Ct-login.uconn.edu")
   at mod_auth_cas.c:1288
3  0x00007ffff62eb221 in cas_authenticate (r=0x7ffff53c30a0) at mod_auth_cas.c:2057
4  0x000055555558fa28 in ap_run_check_user_id ()
5  0x0000555555591d0e in ap_process_request_internal ()
6  0x00005555555a55a0 in ap_process_request ()
7  0x00005555555a23d8 in ?? ()
8  0x000055555559bfa8 in ap_run_process_connection ()
9  0x00005555555aa210 in ?? ()
10 0x00005555555aa936 in ?? ()
11 0x00005555555ab103 in ap_mpm_run ()
12 0x00005555555804a4 in main ()
(gdb)

#### Other:
We really, really need a legitimate (i.e., robust) XML parser.

### CODE REVIEW

**Comment by forsetti** [comment]
@dhawes - #85 indicates this PR fixed issue.  I'm good with committing to master for upcoming 1.0.10 tagging.  @pames ?

**Comment by pames** [comment]
I think this is a net improvement, would still like to see a regression test if possible as this makes it easier to be certain that if the code is refactored at some point (e.g. to use a proper XML parser) we don't reintroduce the bug.

**Comment by dhawes** [comment]
Is this sufficient?

https://github.com/smaresca/mod_auth_cas/compare/saml_segv...dhawes:smaresca-saml_segv?expand=1

**Comment by pames** [comment]
Yes, that looks great (assuming that if we don't apply the diff from @smaresca that everything blows up)

**Comment by smaresca** [comment]
Ha, I will need to take a look at it again first

**Comment by PaulSD** [comment]
Please don't remove lines 1577-1583 of src/mod_auth_cas.c.  (Those lines are currently removed by commit e735f36.)

Those lines extract the AuthenticationMethod attribute from the AuthenticationStatement.  It is true that this is not technically an identity attribute (it is an attribute of the authentication, not an attribute of the identity), but it is a useful attribute none the less.  In my CAS system, we allow both single-factor and two-factor authentication, and I use this attribute to require two-factor authentication for access to certain URLs.  Removing lines 1577-1583 would prevent me from determining the type of authentication that was performed.

If I'm not mistaken, the following unit test should fail when those lines are removed: https://github.com/Jasig/mod_auth_cas/blob/master/tests/mod_auth_cas_test.c#L828
Has anyone run the unit tests against these commits to make sure there are no regressions?

**Comment by dhawes** [comment]
@PaulSD good save. You are correct that the unit tests fail, and I agree that these lines should not be removed.

**Comment by dhawes** [comment]
I can create a pull request with the new test and the AuthenticationStatement extraction back in place against this branch if it's helpful.

I never know if it's easier to do that or just add it to my v1.1 branch.

**Pull request merged**
