### PR TITLE
add apache-2.4 compatibility

### PR DESCRIPTION
**Pull request by klausdieterkrannich**
Added authz provider for apache 2.4.

### CODE REVIEW

**Comment by dgeo** [comment]
I second this: please merge anything better than not-working at all for 2.4 (now default on all distribs) !!!

**Comment by nokru** [comment]
finally got it for Apache 2.4.10 on Debian 8 compiled/module with apache restartet - only thing that is irritating me, is that I get a 500 and "AH01796: AuthType CAS configured without corresponding module, referer: https://intranet.abc.org/" instead of the CAS login page - the config should be fine - works under 2.2 like a charm

any suggestions where start?

**Comment by segui** [comment]
same issue here. got a 500 with @dkdubs mod_auth_cas with error "AH01796: AuthType CAS configured without corresponding module".

apache config just contains "AuthType CAS" and "Require valid-user"

thanks for help

**Comment by segui** [comment]
Mod is working fine alone but seems to fail in a multiple require statement.
the following conf leads to CAS auth, whatever client ip is .... :

                <RequireAny>
                        <RequireAll>
                                Require ip 127.0.0.1 10.1.0.0/24
                        </RequireAll>
                        <RequireAll>
                                AuthType Basic
                                require  cas-attribute user_group_ldap:500
                        </RequireAll>
                </RequireAny>


any clue ?

Thanks

**Comment by dhawes** [comment]
> Mod is working fine alone but seems to fail in a multiple require statement.

mod_auth_cas uses ap_hook_check_access() which runs before authentication so it can redirect you to the CAS server. This happens even if you are using Require(Any|All), so you will always do CAS auth.

I'd have to review the 2.4 documentation, but a quick look seems to show that using the ap_register_auth_provider() (the preferred way to do authnz now) will not allow us to redirect to the CAS server. We could possibly do this by using ap_hook_check_authn() and ap_hook_check_authz() instead of ap_hook_check_access(), but the auth stuff has changed so much in 2.4 that I'm not sure how to get the require line in the authz phase. More investigation is needed.

**Comment by dune73** [comment]
Have been using this in production for a few months now. Works fine.

**Comment by segui** [comment]
That was my guess. Pleased to hear that work is on going on this, sounds
like a needed feature.

Regards,
Christophe

**Comment by forsetti** [comment]
Looks like there are merge conflicts.  @dhawes do we have a vision on the clean patch (something you are using in production?) ?  Yeah, I know ... this one is looong overdue :-/

**Comment by smaresca** [comment]
@forsetti @dhawes Some time ago I rebased against the head of master, resulting in the apache24_support_fixup branch of https://github.com/smaresca/mod_auth_cas and we have used it in production

Want a PR? It preserves attribution to klausdieterkrannich

**Comment by dhawes** [comment]
@forsetti @smaresca The only merge conflict with master is that the declaration for cas_flock() gets stuck in an #ifdef for the new 2.4 authorization functions. It's really as simple as moving the declaration outside of the #ifdef. I can create a PR if that makes things easier.

**Comment by smaresca** [comment]
Go for it, sounds straightforward. I won't have time to touch this until
Monday but I can give the branch a shakedown on our test infrastructure

**Comment by dhawes** [comment]
I created #86 with the resolved conflicts. I'm not sure if that just confuses things, but it's there.

**Comment by forsetti** [comment]
@smaresca Monday test would be great, would love to cut another validation and cut release soon.

**Comment by forsetti** [comment]
@smaresca can you compare #86, #60, and your fixup branch ?

**Comment by dhawes** [comment]
@segui Can you test the patch at https://github.com/Jasig/mod_auth_cas/issues/93#issuecomment-188072306 with the multiple require statements? Thanks in advance.

**Comment by segui** [comment]
@dhawes Works perfectly fine in my environnment. Thanks!

**Pull request merged**
